---
- hosts: master
  become: yes

  tasks:

    - name: Install Java and dependencies
      apt:
        name:
          - openjdk-17-jdk
          - curl
          - gnupg
        state: present
        update_cache: yes

    - name: Remove old Jenkins repo
      file:
        path: /etc/apt/sources.list.d/jenkins.list
        state: absent

    - name: Remove old Jenkins key
      file:
        path: /usr/share/keyrings/jenkins-keyring.asc
        state: absent

    - name: Create keyrings directory
      file:
        path: /usr/share/keyrings
        state: directory
        mode: '0755'

    - name: Add Jenkins GPG key
      shell: |
        curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2026.key | \
        tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null

    - name: Add Jenkins repository
      shell: |
        echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/" | \
        tee /etc/apt/sources.list.d/jenkins.list > /dev/null

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Start Jenkins
      service:
        name: jenkins
        state: started
        enabled: yes


- hosts: agent
  become: yes

  tasks:

    - name: Install Java and Docker
      apt:
        name:
          - openjdk-17-jdk
          - docker.io
        state: present
        update_cache: yes

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes
