---
- hosts: master
  become: yes

  tasks:

    - name: Install Java and dependencies
      apt:
        name:
          - openjdk-17-jdk
          - wget
        state: present
        update_cache: yes

    - name: Create apt keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Jenkins key
      shell: |
        wget -O /etc/apt/keyrings/jenkins-keyring.asc \
        https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key

    - name: Add Jenkins repository
      shell: |
        echo "deb [signed-by=/etc/apt/keyrings/jenkins-keyring.asc] \
        https://pkg.jenkins.io/debian-stable binary/" | tee \
        /etc/apt/sources.list.d/jenkins.list > /dev/null

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Start Jenkins
      service:
        name: jenkins
        state: started
        enabled: yes


- hosts: agent
  become: yes

  tasks:

    - name: Install Java and Docker
      apt:
        name:
          - openjdk-17-jdk
          - docker.io
        state: present
        update_cache: yes

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes
